version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: seo-generator-db
    environment:
      POSTGRES_DB: seo_generator
      POSTGRES_USER: seo_user
      POSTGRES_PASSWORD: seo_password_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - seo-network
    restart: unless-stopped

  # Redis for session storage (optional, for production)
  redis:
    image: redis:7-alpine
    container_name: seo-generator-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - seo-network
    restart: unless-stopped

  # Main Application
  app:
    build: .
    container_name: seo-generator-app
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://seo_user:seo_password_2024@postgres:5432/seo_generator
      REDIS_URL: redis://redis:6379
      SESSION_SECRET: your-super-secret-session-key-change-in-production
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./generated:/app/generated
      - ./database:/app/database
    depends_on:
      - postgres
      - redis
    networks:
      - seo-network
    restart: unless-stopped



volumes:
  postgres_data:
  redis_data:

networks:
  seo-network:
    driver: bridge
